/**
 * Pre-build script that embeds the current git commit hash into the app.
 *
 * Usage:
 *   node node_modules/react-native-github-ota/scripts/embed-commit.js
 *
 * Or add to your package.json scripts:
 *   "prebuild": "node node_modules/react-native-github-ota/scripts/embed-commit.js && npx expo prebuild"
 *
 * Output: constants/buildInfo.ts in the project root.
 */
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

// Resolve project root (4 levels up from scripts/ inside node_modules)
// When installed: node_modules/react-native-github-ota/scripts/embed-commit.js
// When running directly from the package repo itself: scripts/embed-commit.js
let projectRoot = process.cwd(); // default: wherever npm script runs from

const commitHash = execSync("git rev-parse HEAD").toString().trim();
const commitShort = commitHash.slice(0, 7);
const branch = execSync("git rev-parse --abbrev-ref HEAD").toString().trim();
const commitDate = execSync("git log -1 --format=%ci").toString().trim();
const commitMessage = execSync("git log -1 --format=%s").toString().trim();

const config = {
  commitHash,
  commitShort,
  branch,
  commitDate,
  commitMessage,
  buildTime: new Date().toISOString(),
};

const outputDir = path.join(projectRoot, "constants");
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputPath = path.join(outputDir, "buildInfo.ts");

const content = `// Auto-generated by react-native-github-ota/scripts/embed-commit.js — do not edit manually
export const BUILD_INFO = ${JSON.stringify(config, null, 2)} as const;
`;

fs.writeFileSync(outputPath, content, "utf-8");
console.log(`✅ Build info embedded: ${commitShort} (${branch})`);
